#!/usr/bin/env ruby

require 'gluegun'
require 'optparse'


opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage: gluegun COMMAND [OPTIONS]"
  opt.separator  ""
  opt.separator  "Commands"
  opt.separator  "     generate: generates site"
  opt.separator  ""
  opt.separator  "Options"
  opt.on("-h","--help","help") do
    puts opt_parser
  end
end

opt_parser.parse!

case ARGV[0]
when "generate"
  if ARGV[1].nil? || ARGV[1].empty?
    # No config file is provided. Use the default yml file
    site_config = './site.yml'
  else
    site_config = ARGV[1].dup
  end
  Gluegun::Gluegun.generate_sidebar site_config
  Gluegun::Gluegun.gluegun_generate_pages site_config
  Gluegun::Gluegun.gluegun_generate_index site_config
else
  puts opt_parser
end
