Site: "Minio Docs"
Output: "docs"
Documents:  
  - Minio Server: 
      - Minio Server Quick Start Guide: 
        Link: https://github.com/minio/minio/blob/master/README.md
        Slug: minio_server_quickstart_guide

      - Minio Docker Quick Start Guide: 
        Link: https://github.com/minio/minio/blob/master/docs/docker/README.md
        Slug: minio_docker_quickstart_guide

      - Minio Gateway Guide:
        Link: https://github.com/minio/minio/blob/master/docs/gateway/README.md
        Slug: minio_gateway_guide

  - Minio Client: 
      - Minio Client Quick Start Guide: 
        Link: https://github.com/minio/minio/blob/master/docs/minio-limitations.md
        Slug: minio_client_quickstart_guide

      - Minio Client Complete Guide: 
        Link: https://github.com/minio/minio/blob/master/docs/FreeBSD.md
        Slug: minio_client_complete_guide
  
  - Minio SDKs:
      - Multi-tenant Minio Deployment Guide:
        Link: https://github.com/minio/minio/blob/master/docs/multi-tenancy/README.md
        Slug: multi-tenant_minio_deployment_guide

      - Shared Backend Minio Quickstart Guide:
        Link: https://github.com/minio/minio/blob/master/docs/shared-backend/README.md
        Slug: shared_backend_minio_quickstart_guide

  - Minio Cookbook:
      - Minio Limitations:
        Link: https://github.com/minio/minio/blob/master/docs/minio-limitations.md
        Slug: minio_limitations

      - Minio FreeBSD Quickstart Guide:
        Link: https://github.com/minio/minio/blob/master/docs/FreeBSD.md
        Slug: minio_freebsd_quickstart_guide
