Site: "Minio Docs"
Output: "docs"
Documents:  
  - Minio Server: 
      - Minio Server Quick Start Guide: 
        Link: https://github.com/minio/minio/blob/master/README.md

      - Minio Docker Quick Start Guide: 
        Link: https://github.com/minio/minio/blob/master/docs/docker/README.md

      - Minio Gateway Guide:
        Link: https://github.com/minio/minio/blob/master/docs/gateway/README.md

  - Minio Client: 
      - Minio Client Quick Start Guide: 
        Link: https://github.com/minio/minio/blob/master/docs/minio-limitations.md

      - Minio Client Complete Guide: 
        Link: https://github.com/minio/minio/blob/master/docs/FreeBSD.md
  
  - Minio SDKs:
      - Multi-tenant Minio Deployment Guide:
        Link: https://github.com/minio/minio/blob/master/docs/multi-tenancy/README.md

      - Shared Backend Minio Quickstart Guide:
        Link: https://github.com/minio/minio/blob/master/docs/shared-backend/README.md

  - Minio Cookbook:
      - Minio Limitations:
        Link: https://github.com/minio/minio/blob/master/docs/minio-limitations.md
        Slug: minio-limitations

      - Minio FreeBSD Quickstart Guide:
        Link: https://github.com/minio/minio/blob/master/docs/FreeBSD.md
        Slug: minio-freebsd-quickstart-guide
