Site: "Gluegun"
Output: "docs"
Logo: "https://minio.io/img/logo/wordmark_black.svg"

Language:
  - Chinese: https://gluegun.minio.io/cn
  - Japanese: https://gluegun.minio.io/jp

Plugins:
  - Algolia:
      apiKey: "ALGOLIA_TOKEN"
      index: "INDEX_NAME"
  - Google Analytics: "UA-XXXXX-Y"
  - Mixpanel: "MIXPANEL_TOKEN"
  - Footer Widget:
      Label: "Talk to community"
      Link: "/"

Documents:
  - Get Started:
      - Gluegun Quick Start Guide:
        Link: https://github.com/minio/gluegun/blob/master/README.md
        Slug: gluegun-quick-start-guide

  - Theming:
      - Gluegun Theming Guide:
        Link: https://github.com/minio/gluegun/blob/master/README.md
        Slug: gluegun-theming-guide

      - Gluegun Internal Page:
        Link: https://github.com/minio/gluegun/blob/master/README.md
        Slug: gluegun-internal-page
        Options: hidden