Site: "Minio Docs"
Output: "docs"
Logo: "https://minio.io/img/logo/wordmark_white.svg"

Language:
  - Chinese: https://docs.minio.io/cn
  - Japanese: https://docs.minio.io/jp

Plugins:
  # Algolia DocSearch
  - Algolia: 
      apiKey: "0ba0d26da4d1483f96c03fe508304a64"
      index: "minio"
  - Google Analytics: "UA-XXXXX-Y"

Documents:
  - Minio Server:
      - Minio Server Quick Start Guide:
        Link: https://github.com/minio/minio/blob/master/README.md
        Slug: minio-server-quick-start-guide

      - Minio Docker Quick Start Guide:
        Link: https://github.com/minio/minio/blob/master/docs/docker/README.md
        Slug: minio-docker-quick-start-guide

      - Minio Gateway Guide:
        Link: https://github.com/minio/minio/blob/master/docs/gateway/README.md
        Slug: minio-gateway-guide

  - Minio Client:
      - Minio Client Quick Start Guide:
        Link: https://raw.githubusercontent.com/minio/mc/master/README.md

      - Minio Client Complete Guide:
        Link: https://raw.githubusercontent.com/minio/mc/master/docs/minio-client-complete-guide.md
        Slug: minio-client-complete-guide

  - Minio SDKs:
      - JavaScript Client Quickstart Guide:
        Link: https://raw.githubusercontent.com/minio/minio-js/master/README.md

      - JavaScript Client API Referece:
        Link: https://raw.githubusercontent.com/minio/minio-js/master/docs/API.md

  - Minio Cookbook:
      - Minio Limitations:
        Link: https://github.com/minio/minio/blob/master/docs/minio-limitations.md

      - Minio FreeBSD Quickstart Guide:
        Link: https://github.com/minio/minio/blob/master/docs/FreeBSD.md
