Site: "Gluegun"
Output: "docs"
Logo: 
  Image: "https://min.io/resources/img/logo/MINIO_wordmark_black.png"
  Link: "https://min.io"
SEO Author: "MinIO"
Language: "English"

Languages:
  English: "https://gluegun.minio.io/en"
  Chinese: https://gluegun.minio.io/cn
  Japanese: https://gluegun.minio.io/jp 

Plugins:
  - Algolia:
      apiKey: "ALGOLIA_TOKEN"
      index: "INDEX_NAME"
  - Google Analytics: "UA-XXXXX-Y"
  - Mixpanel: "MIXPANEL_TOKEN"
  - Footer Widget:
      Label: "Talk to community"
      Link: "/"

Documents:
  - Get Started:
      - Gluegun Quick Start Guide:
        Link: https://github.com/minio/gluegun/blob/master/README.md
        Slug: gluegun-quick-start-guide
        SEO Title: "Gluegun | Quick Start Guide"
        SEO Description: "Learn how to get started with Gluegun."
        SEO Keywords: "Gluegun, generate documentation, MinIO"
        SEO Languages:
          - Chinese

  - Theming:
      - Gluegun Theming Guide:
        Link: https://github.com/minio/gluegun/blob/master/README.md
        Slug: gluegun-theming-guide
        SEO Title: "Gluegun | Theming Guide"
        SEO Description: "Learn how to theme documentation generated with Gluegun."
        SEO Keywords: "Gluegun, theme documentation pages, MinIO"

      - Gluegun Internal Page:
        Link: https://github.com/minio/gluegun/blob/master/README.md
        Slug: gluegun-internal-page
        SEO Title: "Gluegun | Internal Page"
        SEO Description: "Explore this internal page not visible on the sidebar."
        SEO Keywords: "Gluegun, internal page"
        Options: hidden